### PR TITLE
python3 prints

### PR DESCRIPTION
**Pull request by fchapoton**
you should also remove the restriction in setup.py on python version < 3

### CODE REVIEW

**Comment by fchapoton** [comment]
ping ? sage is now using python3

**Comment by giove91** [comment]
> ping ? sage is now using python3

Thanks for pointing that out!
We are working on updating the code to Python 3, while maintaining compatibility with Python 2. Unfortunately it is not only a matter of prints.

**Comment by giove91** [comment]
Done.
We should test with both Sage 8 / Python 2 and Sage 9 / Python 3, before releasing a new version.

**Comment by giove91** [comment]
I released the new version!
Test with Sage 9 / Python 3 is welcome.

**Pull request merged**
